spring:
  config:
    activate:
      on-profile: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1042140730319-jbjr40o34unb8ukbvhkotic2apbhduh0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

