spring:
  config:
    activate:
      on-profile: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mariadb://footprint-rds-mariadb.ckh8l2wsjl3e.ap-northeast-2.rds.amazonaws.com:3306/footprint?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: footprintRdsSecret1!
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect